# Generated by Django 6.0.2 on 2026-02-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='frames/'),
        ),
        migrations.AddField(
            model_name='job',
            name='input_mode',
            field=models.CharField(choices=[('video', 'Video'), ('frame', 'Frame')], default='video', max_length=16),
        ),
    ]
