# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_frame_image_job_input_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='calibration_status',
            field=models.CharField(choices=[('not_set', 'Not Set'), ('ready', 'Ready'), ('error', 'Error')], default='not_set', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_canvas_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_canvas_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_frames/'),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_frame_time',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_quad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_rectified_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_rectified/'),
        ),
    ]
