# Generated by Django 6.0.2 on 2026-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_calibration_status_job_reference_canvas_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='combination_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hold_annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='hold_annotated/'),
        ),
        migrations.AddField(
            model_name='job',
            name='hold_overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='hold_overlays/'),
        ),
        migrations.AddField(
            model_name='job',
            name='holds_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='projected_holds_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='projected_pose_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
