# Generated by Django 6.0.2 on 2026-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_pose_result_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clean_summary_image',
            field=models.ImageField(blank=True, null=True, upload_to='clean_summaries/'),
        ),
    ]
